name: Deploy Base to Pages

on:
  push:
    branches:
      - main 

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    steps:
      - name: Install Node
        run: sudo apt update && sudo apt install nodejs
      - name: Install Dependencies
        run: node i 
      - name: Run server
        run: npm run start

deploy:
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  needs: build
